POST http://localhost:8000/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MWI1YjEyMDVhYTJjNzY0MjkwYjRjNSIsInVzZXJOYW1lIjoibW9uaSIsImlhdCI6MTY4MTMwMjk1OCwiZXhwIjoxNjgxOTA3NzU4fQ.j8Qng-o1Y-jg3qbDIfqDIQfngIeBkDKmDd9SkFiiYpU

{
  "Name": "Pantalon rojo",
  "Price": 140015001600,
  "Date": 230605,
  "Size": "T2, T4, T6",
  "Material": "Polar",
  "Stuffing": "none",
  "Type": "invierno",
  "Status": "on",
  "Img": "https://i.postimg.cc/sD1ddj7s/66-min.jpg"
}
###

POST http://localhost:8000/api/products
Content-Type: application/json

{}

