POST http://localhost:8000/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MWI1YjEyMDVhYTJjNzY0MjkwYjRjNSIsInVzZXJOYW1lIjoibW9uaSIsImlhdCI6MTY4MTMwMjk1OCwiZXhwIjoxNjgxOTA3NzU4fQ.j8Qng-o1Y-jg3qbDIfqDIQfngIeBkDKmDd9SkFiiYpU

{
  "Name": "Bufanda autitos",
  "Price": 800,
  "Date": 230424,
  "Size": "100x17cm",
  "Material": "Polar",
  "Stuffing": "none",
  "Type": "invierno",
  "Status": "on",
  "Img": ""
}
###

POST http://localhost:8000/api/products
Content-Type: application/json

{}